# -*- coding: utf-8 -*-
"""practical10 nested loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BT-SnimAxwVyB-eSDGcz1EqI6S2K-KrT
"""

l1=[1,2,3,4,5,6,7,8,9,10]
l2=[1,2,3]
for i in l1:
  for j in l2:
    print(f'l1......{i},l2......{j}')

str1='jaipur'
str2='delhi'
for i in str1:
  for j in str2:
    print(i,j)

t1=(1,2,3,4)
t2=(7,8,9,10)
for i in t1:
  for j in t2:
    print(f'{j},{i}')

# #control statement
# #in loop condition
# #break
# continue
# pass

#else


#break.....terminate loop permanently before actual loop completion
for i in range(1,5):
  if i==3:
    break
  print(i)

#continue.........skips the rest of the code for the current iteration
for i in range(1,5):
  if i==3:
   continue
  print(i)

#pass.......(placeholder)no specific purpose
for i in range(1,5):
  if i==3:
   pass
  print(i)

#else
for i in range(1,5):
  print(i)
else:
 print("loop finished")

#practice
for i in range(1,10):
 if i==3:
  break
print(i)

for i in range(1,10):
  if i ==1:
    continue
  print(i)

for i in range(1,10):
  if i ==4:
   pass
  print(i)

#enumerate function-give element with its index
l1=['a','b','c']
for index,i in enumerate(l1):
  print(index,i)